// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/audit.proto

package audit

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogRequest_Actions int32

const (
	LogRequest_REGISTER LogRequest_Actions = 0
	LogRequest_LOGIN    LogRequest_Actions = 1
	LogRequest_CREATE   LogRequest_Actions = 2
	LogRequest_GET      LogRequest_Actions = 3
	LogRequest_UPDATE   LogRequest_Actions = 4
	LogRequest_DELETE   LogRequest_Actions = 5
)

var LogRequest_Actions_name = map[int32]string{
	0: "REGISTER",
	1: "LOGIN",
	2: "CREATE",
	3: "GET",
	4: "UPDATE",
	5: "DELETE",
}

var LogRequest_Actions_value = map[string]int32{
	"REGISTER": 0,
	"LOGIN":    1,
	"CREATE":   2,
	"GET":      3,
	"UPDATE":   4,
	"DELETE":   5,
}

func (x LogRequest_Actions) String() string {
	return proto.EnumName(LogRequest_Actions_name, int32(x))
}

func (LogRequest_Actions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_99c4cf2c975ba637, []int{0, 0}
}

type LogRequest_Entities int32

const (
	LogRequest_ACTOR LogRequest_Entities = 0
	LogRequest_USER  LogRequest_Entities = 1
)

var LogRequest_Entities_name = map[int32]string{
	0: "ACTOR",
	1: "USER",
}

var LogRequest_Entities_value = map[string]int32{
	"ACTOR": 0,
	"USER":  1,
}

func (x LogRequest_Entities) String() string {
	return proto.EnumName(LogRequest_Entities_name, int32(x))
}

func (LogRequest_Entities) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_99c4cf2c975ba637, []int{0, 1}
}

type LogRequest struct {
	Action               LogRequest_Actions   `protobuf:"varint,1,opt,name=action,proto3,enum=audit.LogRequest_Actions" json:"action,omitempty"`
	Entity               LogRequest_Entities  `protobuf:"varint,2,opt,name=entity,proto3,enum=audit.LogRequest_Entities" json:"entity,omitempty"`
	EntityId             int64                `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99c4cf2c975ba637, []int{0}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetAction() LogRequest_Actions {
	if m != nil {
		return m.Action
	}
	return LogRequest_REGISTER
}

func (m *LogRequest) GetEntity() LogRequest_Entities {
	if m != nil {
		return m.Entity
	}
	return LogRequest_ACTOR
}

func (m *LogRequest) GetEntityId() int64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *LogRequest) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_99c4cf2c975ba637, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("audit.LogRequest_Actions", LogRequest_Actions_name, LogRequest_Actions_value)
	proto.RegisterEnum("audit.LogRequest_Entities", LogRequest_Entities_name, LogRequest_Entities_value)
	proto.RegisterType((*LogRequest)(nil), "audit.LogRequest")
	proto.RegisterType((*Empty)(nil), "audit.Empty")
}

func init() { proto.RegisterFile("proto/audit.proto", fileDescriptor_99c4cf2c975ba637) }

var fileDescriptor_99c4cf2c975ba637 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x6e, 0xb2, 0x40,
	0x14, 0x85, 0x45, 0x04, 0xf1, 0xfe, 0xfe, 0x2d, 0xce, 0x8a, 0xd2, 0x85, 0x86, 0x15, 0xab, 0x21,
	0xa5, 0x1b, 0xb7, 0x54, 0x27, 0xc6, 0x84, 0xd4, 0x66, 0xc4, 0x4d, 0x37, 0x0d, 0xca, 0x94, 0x4c,
	0x5a, 0x1c, 0x2a, 0x63, 0x13, 0xdf, 0xad, 0x0f, 0xd7, 0x30, 0x60, 0x5d, 0xb8, 0xbb, 0x73, 0xee,
	0x77, 0x4f, 0xce, 0x19, 0x18, 0x95, 0x07, 0x21, 0x45, 0x90, 0x1e, 0x33, 0x2e, 0xb1, 0x9a, 0x91,
	0xa1, 0x1e, 0xee, 0x38, 0x17, 0x22, 0xff, 0x64, 0x81, 0x12, 0xb7, 0xc7, 0xf7, 0x40, 0xf2, 0x82,
	0x55, 0x32, 0x2d, 0xca, 0x86, 0xf3, 0x7e, 0xba, 0x00, 0xb1, 0xc8, 0x29, 0xfb, 0x3a, 0xb2, 0x4a,
	0xa2, 0x07, 0x30, 0xd3, 0x9d, 0xe4, 0x62, 0xef, 0x68, 0x13, 0xcd, 0xbf, 0x09, 0xef, 0x70, 0x63,
	0x7a, 0x41, 0x70, 0xa4, 0xf6, 0x15, 0x6d, 0x41, 0x14, 0x82, 0xc9, 0xf6, 0x92, 0xcb, 0x93, 0xd3,
	0x55, 0x27, 0xee, 0xf5, 0x09, 0xa9, 0xf7, 0x9c, 0x55, 0xb4, 0x25, 0xd1, 0x3d, 0x0c, 0x9a, 0xe9,
	0x8d, 0x67, 0x8e, 0x3e, 0xd1, 0x7c, 0x9d, 0x5a, 0x8d, 0xb0, 0xcc, 0xd0, 0x14, 0x06, 0x7f, 0x29,
	0x9d, 0xde, 0x44, 0xf3, 0xff, 0x85, 0x2e, 0x6e, 0x7a, 0xe0, 0x73, 0x0f, 0x9c, 0x9c, 0x09, 0x7a,
	0x81, 0xbd, 0x15, 0xf4, 0xdb, 0x74, 0x68, 0x08, 0x16, 0x25, 0x8b, 0xe5, 0x3a, 0x21, 0xd4, 0xee,
	0xa0, 0x01, 0x18, 0xf1, 0x6a, 0xb1, 0x7c, 0xb6, 0x35, 0x04, 0x60, 0xce, 0x28, 0x89, 0x12, 0x62,
	0x77, 0x51, 0x1f, 0xf4, 0x05, 0x49, 0x6c, 0xbd, 0x16, 0x37, 0x2f, 0xf3, 0x5a, 0xec, 0xd5, 0xf3,
	0x9c, 0xc4, 0x24, 0x21, 0xb6, 0xe1, 0x8d, 0xc1, 0x3a, 0x67, 0xaf, 0x3d, 0xa2, 0x59, 0xb2, 0xaa,
	0xed, 0x2c, 0xe8, 0x6d, 0xd6, 0x84, 0xda, 0x9a, 0xd7, 0x07, 0x83, 0x14, 0xa5, 0x3c, 0x85, 0x53,
	0x18, 0x46, 0x75, 0xed, 0x35, 0x3b, 0x7c, 0xf3, 0x1d, 0x43, 0x3e, 0xe8, 0xb1, 0xc8, 0xd1, 0xe8,
	0xea, 0x33, 0xdc, 0x61, 0x2b, 0xa9, 0x3b, 0xaf, 0xf3, 0x74, 0xfb, 0xfa, 0x1f, 0xe3, 0xa0, 0xfc,
	0xc8, 0x83, 0x4c, 0x14, 0x29, 0xdf, 0x6f, 0x4d, 0x55, 0xf2, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x17, 0x87, 0xae, 0xd6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuditServiceClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
}

type auditServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuditServiceClient(cc *grpc.ClientConn) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/audit.AuditService/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
type AuditServiceServer interface {
	Log(context.Context, *LogRequest) (*Empty, error)
}

// UnimplementedAuditServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuditServiceServer struct {
}

func (*UnimplementedAuditServiceServer) Log(ctx context.Context, req *LogRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}

func RegisterAuditServiceServer(s *grpc.Server, srv AuditServiceServer) {
	s.RegisterService(&_AuditService_serviceDesc, srv)
}

func _AuditService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/audit.AuditService/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuditService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "audit.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _AuditService_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/audit.proto",
}
